# Generated by Django 6.1.1 on 2026-09-26 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispensing', '0004_consultation_cleanup'),
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('WARNING', 'Warning'), ('NOT_APPLICABLE', 'Not Applicable'), ('NOT_CHECKED', 'Not Checked')], default='NOT_CHECKED', max_length=20)),
                ('medicine_fingerprint', models.CharField(blank=True, max_length=255)),
                ('checked_pairs', models.PositiveIntegerField(default=0)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_review', to='dispensing.dispensingtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='DrugInteractionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('recommendation', models.TextField()),
                ('source_reference', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interaction_rules_as_a', to='medicines.medicine')),
                ('medicine_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interaction_rules_as_b', to='medicines.medicine')),
            ],
            options={
                'ordering': ['-severity', 'medicine_a__generic_name', 'medicine_b__generic_name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('DRUG_INTERACTION', 'Drug Interaction'), ('ALLERGY', 'Allergy'), ('DOSAGE', 'Dosage')], default='DRUG_INTERACTION', max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('WARNING', 'Warning'), ('NOT_APPLICABLE', 'Not Applicable'), ('NOT_CHECKED', 'Not Checked')], default='WARNING', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('explanation', models.TextField()),
                ('recommendation', models.TextField()),
                ('source_reference', models.CharField(max_length=500)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_clinical_alerts', to=settings.AUTH_USER_MODEL)),
                ('medicine_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_alerts_as_a', to='medicines.medicine')),
                ('medicine_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_alerts_as_b', to='medicines.medicine')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_alerts', to='dispensing.dispensingtransaction')),
                ('rule_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='clinical.druginteractionrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='druginteractionrule',
            constraint=models.UniqueConstraint(fields=('medicine_a', 'medicine_b'), name='unique_canonical_interaction_pair'),
        ),
        migrations.AddConstraint(
            model_name='druginteractionrule',
            constraint=models.CheckConstraint(condition=models.Q(('medicine_a_id__lt', models.F('medicine_b_id'))), name='canonical_interaction_pair_order'),
        ),
        migrations.AddConstraint(
            model_name='clinicalalert',
            constraint=models.UniqueConstraint(fields=('transaction', 'alert_type', 'rule_reference'), name='unique_transaction_rule_alert'),
        ),
    ]
