# Generated by Django 6.1.1 on 2026-09-27 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_interaction_reviews(apps, schema_editor):
    ClinicalReview = apps.get_model('clinical', 'ClinicalReview')
    ClinicalCheckResult = apps.get_model('clinical', 'ClinicalCheckResult')
    for review in ClinicalReview.objects.all().iterator():
        ClinicalCheckResult.objects.get_or_create(
            transaction_id=review.transaction_id,
            check_type='DRUG_INTERACTION',
            defaults={
                'status': review.status,
                'input_fingerprint': review.medicine_fingerprint,
                'checked_at': review.checked_at,
                'details': {
                    'checked_pairs': review.checked_pairs,
                    'execution_failed': review.status == 'NOT_CHECKED',
                    'migrated_from_milestone_7': True,
                },
            },
        )


def remove_migrated_interaction_results(apps, schema_editor):
    ClinicalCheckResult = apps.get_model('clinical', 'ClinicalCheckResult')
    ClinicalCheckResult.objects.filter(details__migrated_from_milestone_7=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('dispensing', '0004_consultation_cleanup'),
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('DRUG_INTERACTION', 'Drug Interaction'), ('ALLERGY', 'Allergy')], max_length=30)),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('WARNING', 'Warning'), ('NOT_APPLICABLE', 'Not Applicable'), ('NOT_CHECKED', 'Not Checked')], default='NOT_CHECKED', max_length=20)),
                ('input_fingerprint', models.CharField(blank=True, max_length=500)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['check_type'],
            },
        ),
        migrations.AlterField(
            model_name='clinicalalert',
            name='medicine_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_alerts_as_b', to='medicines.medicine'),
        ),
        migrations.AddField(
            model_name='clinicalalert',
            name='allergen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_alerts', to='clinical.allergen'),
        ),
        migrations.CreateModel(
            name='AllergyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('recommendation', models.TextField()),
                ('source_reference', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicine_rules', to='clinical.allergen')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allergy_rules', to='medicines.medicine')),
            ],
            options={
                'ordering': ['-severity', 'allergen__name', 'medicine__generic_name'],
            },
        ),
        migrations.AddField(
            model_name='clinicalalert',
            name='allergy_rule_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='clinical.allergyrule'),
        ),
        migrations.AddConstraint(
            model_name='clinicalalert',
            constraint=models.UniqueConstraint(fields=('transaction', 'alert_type', 'allergy_rule_reference'), name='unique_transaction_allergy_rule_alert'),
        ),
        migrations.AddField(
            model_name='clinicalcheckresult',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_check_results', to='dispensing.dispensingtransaction'),
        ),
        migrations.AddConstraint(
            model_name='allergyrule',
            constraint=models.UniqueConstraint(fields=('medicine', 'allergen'), name='unique_medicine_allergen_rule'),
        ),
        migrations.AddConstraint(
            model_name='clinicalcheckresult',
            constraint=models.UniqueConstraint(fields=('transaction', 'check_type'), name='unique_transaction_clinical_check'),
        ),
        migrations.RunPython(preserve_existing_interaction_reviews, remove_migrated_interaction_results),
    ]
