# Generated by Django 6.1.1 on 2026-09-28 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_allergen_clinicalcheckresult_and_more'),
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalalert',
            name='dosage_reason',
            field=models.CharField(blank=True, choices=[('BELOW_SINGLE_DOSE', 'Below single dose'), ('ABOVE_SINGLE_DOSE', 'Above single dose'), ('ABOVE_DAILY_DOSE', 'Above daily dose'), ('FREQUENCY_TOO_LOW', 'Frequency too low'), ('FREQUENCY_TOO_HIGH', 'Frequency too high'), ('DURATION_TOO_LONG', 'Duration too long')], max_length=40),
        ),
        migrations.AddField(
            model_name='clinicalalert',
            name='snapshot_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='clinicalcheckresult',
            name='check_type',
            field=models.CharField(choices=[('DRUG_INTERACTION', 'Drug Interaction'), ('ALLERGY', 'Allergy'), ('DOSAGE', 'Dosage')], max_length=30),
        ),
        migrations.CreateModel(
            name='DosageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_unit', models.CharField(choices=[('MG', 'mg'), ('G', 'g'), ('MCG', 'mcg'), ('ML', 'mL'), ('TABLET', 'tablet'), ('CAPSULE', 'capsule'), ('UNIT', 'unit')], max_length=20)),
                ('min_single_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_single_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_daily_dose', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('min_frequency_per_day', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('max_frequency_per_day', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('max_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('min_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('recommendation', models.TextField()),
                ('source_reference', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dosage_rules', to='medicines.medicine')),
            ],
            options={
                'ordering': ['medicine__generic_name', 'dose_unit', '-severity'],
            },
        ),
        migrations.AddField(
            model_name='clinicalalert',
            name='dosage_rule_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='clinical.dosagerule'),
        ),
    ]
