# Generated by Django 6.1.1 on 2026-09-28 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def migrate_existing_rule_governance(apps, schema_editor):
    audit = apps.get_model('clinical', 'ClinicalRuleAudit')
    now = timezone.now()
    for model_name in ('DrugInteractionRule', 'AllergyRule', 'DosageRule'):
        model = apps.get_model('clinical', model_name)
        for rule in model.objects.all():
            if rule.is_active:
                rule.status = 'ACTIVE'
            else:
                rule.status = 'RETIRED'
                rule.retired_at = now
            rule.change_reason = 'Migrated from legacy is_active state; approval provenance was not available.'
            rule.save(update_fields=['status', 'retired_at', 'change_reason'])
            audit.objects.create(
                rule_type=model_name, rule_object_id=rule.pk, rule_version=1,
                action='MIGRATED', change_reason=rule.change_reason,
                before_snapshot={'is_active': rule.is_active},
                after_snapshot={'status': rule.status, 'version': 1, 'approval_provenance': 'UNKNOWN'},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_clinicalalert_dosage_reason_and_more'),
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRuleAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=40)),
                ('rule_object_id', models.PositiveBigIntegerField()),
                ('rule_version', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('MIGRATED', 'Migrated'), ('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED_FOR_REVIEW', 'Submitted for Review'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('ACTIVATED', 'Activated'), ('RETIRED', 'Retired'), ('SUPERSEDED', 'Superseded')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-changed_at', '-pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='allergyrule',
            name='unique_medicine_allergen_rule',
        ),
        migrations.RemoveConstraint(
            model_name='druginteractionrule',
            name='unique_canonical_interaction_pair',
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='change_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='effective_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='retired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retired_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='source_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='source_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='source_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_versions', to='clinical.allergyrule'),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='change_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='effective_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='retired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retired_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='source_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='source_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='source_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_versions', to='clinical.dosagerule'),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='change_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='effective_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='retired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retired_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='source_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='source_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='source_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_versions', to='clinical.druginteractionrule'),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='allergyrule',
            constraint=models.UniqueConstraint(fields=('medicine', 'allergen', 'version'), name='unique_versioned_medicine_allergen_rule'),
        ),
        migrations.AddConstraint(
            model_name='druginteractionrule',
            constraint=models.UniqueConstraint(fields=('medicine_a', 'medicine_b', 'version'), name='unique_versioned_interaction_pair'),
        ),
        migrations.AddField(
            model_name='clinicalruleaudit',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_rule_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_existing_rule_governance, migrations.RunPython.noop),
    ]
