# Generated by Django 6.1.1 on 2026-09-28 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_clinicalruleaudit_and_more'),
        ('dispensing', '0006_dispensingitem_dose_amount_dispensingitem_dose_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRiskModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('model_type', models.CharField(default='DecisionTreeClassifier', max_length=100)),
                ('artifact_path', models.CharField(max_length=500)),
                ('trained_at', models.DateTimeField()),
                ('dataset_name', models.CharField(max_length=255)),
                ('dataset_version', models.CharField(max_length=100)),
                ('feature_schema', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_priority', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('final_priority', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('prediction_probability', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('feature_snapshot', models.JSONField(default=dict)),
                ('decision_path', models.JSONField(default=list)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='dispensing.dispensingtransaction')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='clinical.clinicalriskmodelversion')),
            ],
        ),
    ]
