# Generated by Django 6.1.1 on 2026-10-05 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pharmacy_user_pharmacy'),
        ('clinical', '0005_clinicalriskmodelversion_clinicalriskassessment'),
        ('medicines', '0002_remove_medicine_unique_medicine_formulation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='allergyrule',
            name='unique_versioned_medicine_allergen_rule',
        ),
        migrations.RemoveConstraint(
            model_name='druginteractionrule',
            name='unique_versioned_interaction_pair',
        ),
        migrations.AddField(
            model_name='allergen',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allergens', to='accounts.pharmacy'),
        ),
        migrations.AddField(
            model_name='allergyrule',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allergy_rules', to='accounts.pharmacy'),
        ),
        migrations.AddField(
            model_name='dosagerule',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dosage_rules', to='accounts.pharmacy'),
        ),
        migrations.AddField(
            model_name='druginteractionrule',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drug_interaction_rules', to='accounts.pharmacy'),
        ),
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='allergen',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'name'), name='unique_pharmacy_allergen_name'),
        ),
        migrations.AddConstraint(
            model_name='allergyrule',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'medicine', 'allergen', 'version'), name='unique_versioned_medicine_allergen_rule'),
        ),
        migrations.AddConstraint(
            model_name='druginteractionrule',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'medicine_a', 'medicine_b', 'version'), name='unique_versioned_interaction_pair'),
        ),
    ]
