# Generated by Django 6.1.1 on 2026-10-05 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_default_pharmacy'),
        ('clinical', '0006_remove_allergyrule_unique_versioned_medicine_allergen_rule_and_more'),
        ('medicines', '0002_remove_medicine_unique_medicine_formulation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='allergen',
            constraint=models.UniqueConstraint(condition=models.Q(('pharmacy__isnull', True)), fields=('name',), name='unique_unassigned_allergen_name'),
        ),
        migrations.AddConstraint(
            model_name='allergyrule',
            constraint=models.UniqueConstraint(condition=models.Q(('pharmacy__isnull', True)), fields=('medicine', 'allergen', 'version'), name='unique_unassigned_medicine_allergen_rule'),
        ),
        migrations.AddConstraint(
            model_name='druginteractionrule',
            constraint=models.UniqueConstraint(condition=models.Q(('pharmacy__isnull', True)), fields=('medicine_a', 'medicine_b', 'version'), name='unique_unassigned_interaction_pair'),
        ),
    ]
