# Generated by Django 6.1.1 on 2026-09-18 00:10

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text="The manufacturer's batch or lot number.", max_length=100)),
                ('quantity_received', models.PositiveIntegerField(help_text='The total initial quantity received for this batch.', validators=[django.core.validators.MinValueValidator(1, message='Quantity received must be greater than 0.')])),
                ('quantity_remaining', models.PositiveIntegerField(help_text='The current remaining stock for this batch.')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Cost price per unit.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_received', models.DateField(default=datetime.date.today, help_text='Date the batch was received into inventory.')),
                ('expiry_date', models.DateField(help_text='Expiration date of the batch.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this batch is active. Inactive batches are excluded from available stock.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(help_text='The medicine this batch belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='medicines.medicine')),
            ],
            options={
                'verbose_name': 'Medicine Batch',
                'verbose_name_plural': 'Medicine Batches',
                'ordering': ['expiry_date', 'date_received'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('ADJUSTMENT_INCREASE', 'Adjustment (Increase)'), ('ADJUSTMENT_DECREASE', 'Adjustment (Decrease)'), ('DISPENSED', 'Dispensed')], max_length=50)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity involved in the transaction.')),
                ('previous_quantity', models.PositiveIntegerField(help_text='Quantity remaining before the transaction.')),
                ('new_quantity', models.PositiveIntegerField(help_text='Quantity remaining after the transaction.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes for adjustments or corrections.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.medicinebatch')),
                ('user', models.ForeignKey(help_text='User who performed the transaction.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.UniqueConstraint(fields=('medicine', 'batch_number'), name='unique_medicine_batch'),
        ),
    ]
