# Generated by Django 6.1.1 on 2026-09-16 23:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the medicine category (e.g., Analgesics, Antibiotics).', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this category is active in the pharmacy catalog.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine Category',
                'verbose_name_plural': 'Medicine Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(help_text='Generic or scientific name (e.g., Paracetamol, Amoxicillin).', max_length=255)),
                ('brand_name', models.CharField(blank=True, help_text='Commercial or brand name (e.g., Panadol, Amoxil), if applicable.', max_length=255)),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('SUSPENSION', 'Suspension'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('POWDER', 'Powder'), ('OTHER', 'Other')], help_text='Formulation of the drug.', max_length=50)),
                ('strength', models.CharField(help_text='Strength or concentration (e.g., 500mg, 250mg/5ml).', max_length=100)),
                ('unit', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('bottle', 'Bottle'), ('vial', 'Vial'), ('ampoule', 'Ampoule'), ('sachet', 'Sachet'), ('tube', 'Tube'), ('pack', 'Pack'), ('ml', 'ml'), ('unit', 'Unit'), ('other', 'Other')], help_text='Standard dispensing unit.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional clinical notes, storage instructions, or indications.')),
                ('minimum_stock_level', models.PositiveIntegerField(default=10, help_text='Threshold quantity below which low-stock alerts are triggered.', validators=[django.core.validators.MinValueValidator(0, message='Minimum stock level cannot be negative.')])),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this medicine is active in the pharmacy catalog.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category this medicine belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='medicines.medicinecategory')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['generic_name', 'brand_name'],
                'constraints': [models.UniqueConstraint(fields=('generic_name', 'brand_name', 'strength', 'dosage_form'), name='unique_medicine_formulation')],
            },
        ),
    ]
