# Generated by Django 6.1.1 on 2026-10-05 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pharmacy_user_pharmacy'),
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicine',
            name='unique_medicine_formulation',
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='accounts.pharmacy'),
        ),
        migrations.AddField(
            model_name='medicinecategory',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicine_categories', to='accounts.pharmacy'),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='name',
            field=models.CharField(help_text='Unique name of the medicine category (e.g., Analgesics, Antibiotics).', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'generic_name', 'brand_name', 'strength', 'dosage_form'), name='unique_medicine_formulation'),
        ),
        migrations.AddConstraint(
            model_name='medicinecategory',
            constraint=models.UniqueConstraint(fields=('pharmacy', 'name'), name='unique_pharmacy_category_name'),
        ),
    ]
