# Generated by Django 6.1.1 on 2026-10-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_default_pharmacy'),
        ('medicines', '0002_remove_medicine_unique_medicine_formulation_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(condition=models.Q(('pharmacy__isnull', True)), fields=('generic_name', 'brand_name', 'strength', 'dosage_form'), name='unique_unassigned_medicine_formulation'),
        ),
        migrations.AddConstraint(
            model_name='medicinecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('pharmacy__isnull', True)), fields=('name',), name='unique_unassigned_category_name'),
        ),
    ]
