# Generated by Django 6.1.1 on 2026-09-21 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_stocktransaction_reference_number'),
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(blank=True, db_index=True, help_text='Auto-generated after initial save. Format: DS-YYYY-NNNNNN.', max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('DIRECT_SALE', 'Direct Sale'), ('EXTERNAL_PRESCRIPTION', 'External Prescription'), ('CONSULTATION', 'Consultation')], default='DIRECT_SALE', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all line totals (before any discounts/taxes).', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Final amount charged.', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Set when transaction status changes to COMPLETED.', null=True)),
                ('user', models.ForeignKey(help_text='Staff member who created this transaction.', on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispensing Transaction',
                'verbose_name_plural': 'Dispensing Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispensingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Units dispensed from this specific batch.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit at the time of dispensing (from MedicineBatch.selling_price).', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='quantity × unit_price.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_items', to='inventory.medicinebatch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_items', to='medicines.medicine')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dispensing.dispensingtransaction')),
            ],
            options={
                'verbose_name': 'Dispensing Item',
                'verbose_name_plural': 'Dispensing Items',
                'ordering': ['transaction', 'medicine__generic_name'],
            },
        ),
    ]
