# Generated by Django 6.1.1 on 2026-09-22 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensingitem',
            name='dose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispensingitem',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispensingitem',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispensingitem',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispensingtransaction',
            name='transaction_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated after initial save. Format: TX-YYYY-NNNNNN.', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ExternalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_source', models.CharField(blank=True, choices=[('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('DOCTOR', 'Doctor'), ('COMMUNITY_HEALTH_CENTER', 'Community Health Center'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('prescriber_name', models.CharField(blank=True, max_length=200, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=200, null=True)),
                ('prescription_date', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_prescription', to='dispensing.dispensingtransaction')),
            ],
            options={
                'verbose_name': 'External Prescription',
                'verbose_name_plural': 'External Prescriptions',
            },
        ),
    ]
