# Generated by Django 6.1.1 on 2026-09-22 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing', '0002_dispensingitem_dose_dispensingitem_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('symptoms', models.TextField(help_text='Required')),
                ('known_allergies', models.TextField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('pregnancy_status', models.CharField(blank=True, choices=[('NOT_PREGNANT', 'Not Pregnant'), ('PREGNANT', 'Pregnant'), ('UNKNOWN', 'Unknown / Not Applicable')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='dispensing.dispensingtransaction')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
            },
        ),
    ]
