# Generated by Django 6.1.1 on 2026-09-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing', '0003_consultation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='patient_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='patient_gender',
            new_name='sex',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='consultation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='symptom_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
