# Generated by Django 6.1.1 on 2026-09-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_allergen_clinicalcheckresult_and_more'),
        ('dispensing', '0004_consultation_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='structured_allergies',
            field=models.ManyToManyField(blank=True, help_text='Structured allergies included in automated allergy checking.', related_name='consultations', to='clinical.allergen'),
        ),
    ]
