# Generated by Django 6.1.1 on 2026-09-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing', '0005_consultation_structured_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensingitem',
            name='dose_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dispensingitem',
            name='dose_unit',
            field=models.CharField(blank=True, choices=[('MG', 'mg'), ('G', 'g'), ('MCG', 'mcg'), ('ML', 'mL'), ('TABLET', 'tablet'), ('CAPSULE', 'capsule'), ('UNIT', 'unit')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dispensingitem',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispensingitem',
            name='frequency_per_day',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
