# Generated by Django 6.1.1 on 2026-10-05 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pharmacy_user_pharmacy'),
        ('dispensing', '0006_dispensingitem_dose_amount_dispensingitem_dose_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensingtransaction',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispensing_transactions', to='accounts.pharmacy'),
        ),
    ]
